const transactions = [
  {
    id: 1,
    title: "Salary",
    amount: 50000,
    type: "income",
    category: "Salary",
    date: "2026-04-01",
    notes: "April salary credited",
  },
  {
    id: 2,
    title: "Groceries",
    amount: 2500,
    type: "expense",
    category: "Food",
    date: "2026-04-02",
    notes: "Weekly grocery shopping",
  },
  {
    id: 3,
    title: "Electricity Bill",
    amount: 1800,
    type: "expense",
    category: "Bills",
    date: "2026-04-03",
    notes: "EB bill payment",
  },
  {
    id: 4,
    title: "Freelance Project",
    amount: 12000,
    type: "income",
    category: "Freelance",
    date: "2026-04-04",
    notes: "Website development",
  },
  {
    id: 5,
    title: "Dining Out",
    amount: 900,
    type: "expense",
    category: "Food",
    date: "2026-04-05",
    notes: "Dinner with friends",
  },
  {
    id: 6,
    title: "Petrol",
    amount: 1500,
    type: "expense",
    category: "Transport",
    date: "2026-04-06",
    notes: "Fuel refill",
  },
  {
    id: 7,
    title: "Movie",
    amount: 600,
    type: "expense",
    category: "Entertainment",
    date: "2026-04-07",
    notes: "Weekend movie",
  },
  {
    id: 8,
    title: "Internet Bill",
    amount: 999,
    type: "expense",
    category: "Bills",
    date: "2026-04-08",
    notes: "Monthly broadband",
  },
  {
    id: 9,
    title: "Stock Dividend",
    amount: 2000,
    type: "income",
    category: "Investment",
    date: "2026-04-09",
    notes: "Dividend received",
  },
  {
    id: 10,
    title: "Gym Membership",
    amount: 1500,
    type: "expense",
    category: "Health",
    date: "2026-04-10",
    notes: "Monthly gym fee",
  },
  {
    id: 11,
    title: "Mobile Recharge",
    amount: 399,
    type: "expense",
    category: "Bills",
    date: "2026-04-11",
    notes: "Prepaid recharge",
  },
  {
    id: 12,
    title: "Clothing",
    amount: 3000,
    type: "expense",
    category: "Shopping",
    date: "2026-04-12",
    notes: "Bought new clothes",
  },
  {
    id: 13,
    title: "Bonus",
    amount: 10000,
    type: "income",
    category: "Salary",
    date: "2026-04-13",
    notes: "Performance bonus",
  },
  {
    id: 14,
    title: "Uber Ride",
    amount: 250,
    type: "expense",
    category: "Transport",
    date: "2026-04-14",
    notes: "Office commute",
  },
  {
    id: 15,
    title: "Coffee",
    amount: 150,
    type: "expense",
    category: "Food",
    date: "2026-04-15",
    notes: "Evening coffee",
  },
  {
    id: 16,
    title: "Mutual Fund Investment",
    amount: 5000,
    type: "expense",
    category: "Investment",
    date: "2026-04-16",
    notes: "SIP investment",
  },
  {
    id: 17,
    title: "Gift Received",
    amount: 2000,
    type: "income",
    category: "Other",
    date: "2026-04-17",
    notes: "Birthday gift",
  },
  {
    id: 18,
    title: "Medical Expense",
    amount: 1200,
    type: "expense",
    category: "Health",
    date: "2026-04-18",
    notes: "Doctor consultation",
  },
  {
    id: 19,
    title: "Book Purchase",
    amount: 500,
    type: "expense",
    category: "Education",
    date: "2026-04-19",
    notes: "Bought programming book",
  },
  {
    id: 20,
    title: "Part-time Income",
    amount: 8000,
    type: "income",
    category: "Freelance",
    date: "2026-04-20",
    notes: "Weekend work",
  },
];

export default transactions;
